mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from polls import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('', views.LandingPage.as_view(), name='landing-page'),
    path('categories/', views.CategoriesView.as_view(), name='categories'),
]

polls/urls.py
from django.urls import path
from . import views


app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<str:slug>/', views.CategoryQuestionView.as_view(), name='category-polls'),
    path('<str:slug>/<int:pk>/', views.DetailView.as_view(), name='question-detail'),
    path('<str:slug>/<int:pk>/results/', views.ResultsView.as_view(), name='question-results'),
    path('<str:slug>/<int:pk>/vote/', views.question_vote, name='vote'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.utils.text import slugify


class Question(models.Model):
    question_text = models.CharField(max_length=250)
    pub_date = models.DateTimeField('date published', default=timezone.now)

    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=250)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class Category(models.Model):
    """
    Representation of the category db table
    """
    name = models.CharField(max_length=160)
    slug = models.SlugField(max_length=160)
    question = models.ManyToManyField(Question)
    description = models.TextField()
    
    def __str__(self):
        """
        Returns human-readable category name
        """
        return self.name

    def save(self, *args, **kwargs):
        """
        Automatically creates slug for category name
        """
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)        
        

polls/views.py
from django.db.models import Count
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.urls import reverse
from django.utils import timezone

from .models import Category, Choice, Question


class LandingPage(generic.TemplateView):
    """
    Landing Page: displays Welcome message and first three categories with questions that got most votes
    """
    template_name = 'polls/landing-page.html'

    def get_context_data(self, **kwargs):
        """
        Passing categories to the context
        """
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of first three category
        context['categories'] = Category.objects.annotate(num_votes=Count('question__choice__votes')).order_by('-num_votes')[:3]
        return context


class CategoriesView(generic.ListView):
    """
    List of all Categories
    """
    model = Category
    template_name = 'polls/categories.html'
    context_object_name = 'categories'
       

class CategoryQuestionView(generic.DetailView):
    """
    Displays all questions related to the specific category
    """
    model = Category
    template_name = 'polls/category-questions.html'


class DetailView(generic.DetailView):
    """
    Displays specific question for with choices for voting
    """
    model = Question
    template_name = 'polls/question-detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet and without choices set.
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).exclude(choice__isnull=True)
    
    def get_context_data(self, **kwargs):
        """
        Passing categories to the context
        """
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of first three category
        context['category'] = Category.objects.get(question=self.object)
        return context

def question_vote(request, slug, pk):
    category = get_object_or_404(Category, slug=slug)
    question = get_object_or_404(Question.objects.filter(pub_date__lte=timezone.now()).exclude(choice__isnull=True), category=category.pk, pk=pk)   
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        #Redisplay the question voting form
        return render(request, 'polls/question-detail.html', {
            'question': question, 
            'category': category,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        #Always return an HttpResponseRedirect after after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:question-results', args=(slug, pk)))

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

    def get_queryset(self):
        """
        Excludes access to any questions that hasn't been published yet and have no choice set
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).exclude(choice__isnull=True)
    
    def get_context_data(self, **kwargs):
        """
        Passing categories to the context
        """
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of first three category
        context['category'] = Category.objects.get(question=self.object)
        return context


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return last five published questions that have choices set
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).exclude(choice__isnull=True).order_by('-pub_date')

polls/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>{% block title %} Voter||Board {% endblock %}</title>
</head>
<body>
    <!-- Just an image navigration -->
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'landing-page' %}">
            <img src="{% static 'polls/images/v.svg' %}" width="30" height="30" alt="" loading="lazy">
        </a>
    </nav>
    <!--Site wrapper-->
    <header class="page-header header container-fluid">
        {% block content %}
        {% endblock %}
    </header>
</body>
</html>

polls/templates/polls/categories.html
{% extends 'polls/base.html' %}

{% load static %}
{% block content %}    
  <div class="container">
    <h3 class="mt-5 mb-5 text-center"><strong>Categories</strong></h3>
    <div class="row">
    {% for category in categories %}
      <div class="col-lg-4 col-md-4 col-sm-12">
        <h3 class="feature-title"><a type="button" class="btn btn-info btn-lg btn-block" href="{% url 'polls:category-polls' category.slug %}">{{ category.name }}</a></h3>
        <!-- <img src="images/column-1.jpg" class="img-fluid"> -->
        <p class="text-center mb-5">{{ category.description }}</p>
      </div>
      {% endfor %}
    </div>
    <div class="text-center">
      <a class="btn btn-outline-info btn-lg" role="button" href="{% url 'polls:index' %}">Show all Polls</a>
    </div>
  </div>
{% endblock %}

polls/templates/polls/category-questions.html
{% extends 'polls/base.html' %}

{% block content %}
<div class="mt-5 container">
    <h3 class="text-center"><strong>Questions</strong></h3>
    {% for question  in category.question.all %}
    {% if question.choice_set.all %}
    <div class="question row">
        <div class="col-8">{{question.question_text}}</div>
        <div class="col-4"><a class="btn btn-outline-info" href="{% url 'polls:question-detail' category.slug question.pk %}">Answer</a></div>
    </div>
    {% endif %}
    {% endfor %}
</div>
        
{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block content %}
<div class="container mt-5">
    <a class="btn btn-outline-info mb-5" role="button" href="{% url 'landing-page' %}">Back Home</a>
    {% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        {% for category in question.category_set.all %}
        <li><a href="{% url 'polls:question-detail' category.slug question.pk %}">{{ question.question_text }}</a></li>
        {% endfor%}
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</div>
{% endblock %}

polls/templates/polls/landing-page.html
{% extends 'polls/base.html' %}
{% load static %}

{% block content %}    
  <div class="description">
    <h1>Welcome to the Voter!</h1>
    <p class="text-muted">Make your vote count</p>
  </div>
  {% if categories %}
  <div class="container features">
    <h3 class="mt-5 mb-5 text-center"><strong>Vote in category</strong></h3>
    <div class="row">
      {% for category in categories%}
        <div class="col-lg-4 col-md-4 col-sm-12">
          <h3 class="feature-title"><a type="submit" class="btn btn-info btn-lg btn-block" href="{% url 'polls:category-polls' category.slug %}">{{ category.name }}</a></h3>
          <p class="text-center">{{ category.description }}</p>
        </div>
      {% endfor %}
    </div>
    <div class="text-center mt-5">
      <a class="btn btn-outline-info btn-lg" role="button" href="{% url 'categories' %}">See all</a>
    </div>
    {% else %}
    <p>No categories created so far. populate_polls_db before lanching an app is required.</p>
    {% endif %}
  </div>
{% endblock %}

polls/templates/polls/question-detail.html
{% extends 'polls/base.html' %}

{% block content %}
<div class="container mt-5">
<a class="btn btn-outline-info mb-5" role="button" href="{% url 'polls:category-polls' category.slug %}">Question category</a>
<a class="btn btn-outline-info mb-5" role="button" href="{% url 'polls:index' %}">All Questions</a>

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' category.slug question.pk %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<button type="submit" value="Vote" class="btn btn-info mt-2">Vote</button>
</form>
</div>
{% endblock %}

polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block content %}
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>
<a href="{% url 'polls:category-polls' category.slug%}">Vote another.</a>
<a href="{% url 'polls:question-detail' category.slug question.pk %}">Vote again?</a>
{% endblock %}